/**
 * Created by melalex on 4/10/17.
 */

const LANGUAGE_KEY = 'LANGUAGE_KEY';
const DEFAULT_LANGUAGE = 'en';

const ERROR_MESSAGE = 'ERROR_MESSAGE';
const INFO_MESSAGE = 'INFO_MESSAGE';
const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export {
    DEFAULT_LANGUAGE,
    LANGUAGE_KEY,
    ERROR_MESSAGE,
    INFO_MESSAGE,
    CLEAN_MESSAGE,
    CHANGE_LANGUAGE
}