/**
 * Created by melalex on 4/10/17.
 */

const ERROR_MESSAGE = 'ERROR_MESSAGE';
const INFO_MESSAGE = 'INFO_MESSAGE';
const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export {
    ERROR_MESSAGE,
    INFO_MESSAGE,
    CLEAN_MESSAGE,
    CHANGE_LANGUAGE
}