/**
 * Created by melalex on 4/10/17.
 */

const MAKE_BET_REQUEST = 'MAKE_BET_REQUEST';
const MAKE_BET_SUCCESS = 'MAKE_BET_SUCCESS';
const MAKE_BET_FAILED = 'MAKE_BET_FAILED';

const GET_ODS_REQUEST = 'GET_ODS_REQUEST';
const GET_ODS_SUCCESS = 'GET_ODS_SUCCESS';
const GET_ODS_FAILED = 'GET_ODS_FAILED';

export {
    MAKE_BET_REQUEST,
    MAKE_BET_SUCCESS,
    MAKE_BET_FAILED,
    GET_ODS_REQUEST,
    GET_ODS_SUCCESS,
    GET_ODS_FAILED,
}