/**
 * Created by melalex on 4/10/17.
 */


const APP_USER_KEY = 'app-client';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILED = 'REGISTER_FAILED';

const REFRESH_REQUEST = 'REFRESH_REQUEST';
const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
const REFRESH_FAILED = 'REFRESH_FAILED';

const LOGOUT = 'LOGOUT';

export {
    APP_USER_KEY,
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER_REQUEST,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    REFRESH_REQUEST,
    REFRESH_SUCCESS,
    REFRESH_FAILED,
    LOGOUT
}