/**
 * Created by melalex on 4/10/17.
 */

const GET_REQUEST = 'GET_REQUEST';
const GET_SUCCESS = 'GET_SUCCESS';
const GET_FAILED = 'GET_FAILED';

const CONTENT_TYPE_RACE = 'CONTENT_TYPE_RACE';
const CONTENT_TYPE_BET = 'CONTENT_TYPE_BET';

export {
    GET_REQUEST,
    GET_SUCCESS,
    GET_FAILED,
    CONTENT_TYPE_RACE,
    CONTENT_TYPE_BET
}